### ISSUE TITLE
Facebook external image links are not translated, they still go over safe-image.php

### ISSUE THREAD

**Issue by iki** [canisbos/DirectLinks#2]
Observed with @au5ton Chrome port https://github.com/au5ton/DirectLinks, but should be probably fixed here at upstream.

Example: https://www.facebook.com/ArtCtrlDel/posts/715637751904568

**Comment by canisbos** [comment]
v1.0.8, just pushed, should fix this.

**Comment by canisbos** [comment]
Actually, I misread the issue. You're talking about the `src` attribute of these images? But why would you want to rewrite the `src`s?

**Comment by iki** [comment]
Thanks for the update. And sorry for late response, I missed the notification.
I meant replacing the giphy link (a href), so it can be copied with Copy link address.

https://github.com/nokeya/direct-links-out does that for example. But you probably added that in v1.0.8 too, right?

**Comment by canisbos** [comment]
I think so. I added code to handle Facebook image links, and I'm assuming it works on all of them. Thanks.
