### ISSUE TITLE
Update to 1.0.12 is broken in Safari

### ISSUE THREAD

**Issue by mokolabs** [canisbos/DirectLinks#6]
FYI... on Safari 11.0.3 and High Sierra 10.13.3, the Update button isn't working for me.

I'm on version 1.10.11. Safari shows an update for 1.10.12, but clicking on the Update button doesn't do anything. I also tried manually reinstalling, but that didn't work either.

I just now downloaded it from here, but I thought you should know something is wonky with the normal update procedure. :)

**Comment by mokolabs** [comment]
Hmmm... actually, I think something is broken in 1.10.12 build. I can't install it manually either. :(

**Comment by mokolabs** [comment]
Update: I just got it to work after a few tries, but still, I think something fishy is going on here.

**Comment by canisbos** [comment]
Yes, something seems to be wrong. If I install 1.10.11 manually and then try to update to 1.10.12 using the button in Safari Preferences, nothing happens. And yet the same URL that's in the Update.plist works if I enter it in the browser's address bar. I don't know what's going on. It could be an issue on Apple's end.

**Comment by canisbos** [comment]
I put the safariextz file in the wrong place. Fixed that, now I've had to increment the version number again to get the update working. Updating should now work.

**Comment by mokolabs** [comment]
Okay, sweet. Thanks!
