### ISSUE TITLE
Move to Safari App Extension or Safari Extensions Gallery

### ISSUE THREAD

**Issue by robmathers** [canisbos/DirectLinks#7]
Unfortunately in Safari 12, coming with 10.14, Safari extensions distributed outside the gallery or app store are being removed. I'd love to keep using DirectLinks, but it looks like it needs to be in the gallery (which is being deprecated, but still kept alive for the moment), or converted to a Safari App Extension. 

More details at https://developer.apple.com/safari/whats-new/

**Comment by canisbos** [comment]
Bummer. I probably won't take the time to port these extensions to the new platform. Apple's decision is unfortunate.

**Comment by VideoPlayerCode** [comment]
@canisbos Apple's decision is very unfortunate. The new Safari is out for 10.13 High Sierra too, and bans all external extensions there too.

It would be possible to put this direct link code in a Tampermonkey userscript at greasyfork.org, but perhaps this is instead a good time for you to quit and take a break from the work of distributing software. I've been there, and it's a burden to constantly have to update things. You had so many extensions to work on.

Thank you for your years of fantastically great extensions. Take care! :)

**Comment by canisbos** [comment]
Thank you, @VideoPlayerCode!
